"""Step captions of the four tutorial videos, in every app language.

record_tutorial_videos.py records each tutorial once per language with the
whole app switched to that language, and burns the caption for the current
step into the picture. Button and menu names inside a caption are written as
{placeholders}; the recorder fills them from src/translations.py, so a caption
always names a control exactly as the viewer sees it in the same video.

Placeholders: new_strand, attach, new_mask, masks (the Masks tab), strands
(the Strands tab), close_knot, dark, ok, change_language.

Keys: s_* = tutorial 1 (themes and language), b_* = tutorial 2 (layer panel
buttons), m_* = tutorial 3 (strands and a mask), k_* = tutorial 4 (a knot).
"""

CAPTIONS = {
    "en": {
        "s_title": "Tutorial: themes and language",
        "s1": "1. Click the Settings (gear) button",
        "s2": "2. Open the theme dropdown and pick '{dark}'",
        "s3": "3. Click {ok} - the whole app switches theme",
        "s4": "4. Open Settings again and pick '{change_language}'",
        "s5": "5. Pick a language, then {ok} - the interface updates",
        "s6": "6. Switch back anytime - settings are saved automatically",
        "s_end": "That's it - make OpenStrand Studio yours!",
        "b_title": "Tutorial: what do the layer panel buttons do?",
        "b1": "1. Hold right-click on any button to see its description",
        "b2": "2. Release to hide it - try the zoom buttons too",
        "b3": "3. The hand button pans the canvas view",
        "b4": "4. Refresh reloads the layers and resets the view",
        "b5": "5. The target button centers your strands",
        "b_end": "Right-click any button you are unsure about - done!",
        "m_title": "Tutorial: crossing strands with a mask",
        "m1": "1. Click '{new_strand}', then drag on the canvas to draw strand 1_1",
        "m2": "2. Click '{attach}', then drag from the end of 1_1 to add strand 1_2",
        "m3": "3. Click '{new_strand}' again to start set 2 - draw strand 2_1",
        "m4": "4. Click '{attach}' and add strand 2_2 - it crosses over strand 1_1",
        "m5": "5. Open the '{masks}' tab and click '{new_mask}'",
        "m6": "6. Click strand 1_1 - it will stay on top",
        "m7": "7. Now click strand 2_2 - it goes under strand 1_1",
        "m8": "8. The mask layer '1_1_2_2' appears in the '{masks}' list",
        "m9": "9. Switch between '{strands}' and '{masks}' to see each list",
        "m_end": "Masks always stay above all strands - done!",
        "k_title": "Tutorial: closing a knot",
        "k1": "1. Click '{new_strand}' and drag to draw strand 1_1",
        "k2": "2. Click '{attach}' and add strand 1_2 from one end of 1_1",
        "k3": "3. Attach strand 1_3 from the other end of 1_1",
        "k4": "4. Right-click layer '1_2' and choose '{close_knot}'",
        "k5": "5. The free ends snap together - you made a closed knot!",
    },
    "fr": {
        "s_title": "Tutoriel : thèmes et langue",
        "s1": "1. Cliquez sur le bouton Paramètres (engrenage)",
        "s2": "2. Ouvrez la liste des thèmes et choisissez '{dark}'",
        "s3": "3. Cliquez sur {ok} - toute l'application change de thème",
        "s4": "4. Rouvrez les Paramètres et choisissez '{change_language}'",
        "s5": "5. Choisissez une langue, puis {ok} - l'interface se met à jour",
        "s6": "6. Revenez en arrière à tout moment - les réglages sont enregistrés automatiquement",
        "s_end": "Voilà - personnalisez OpenStrand Studio !",
        "b_title": "Tutoriel : à quoi servent les boutons du panneau des calques ?",
        "b1": "1. Maintenez le clic droit sur un bouton pour voir sa description",
        "b2": "2. Relâchez pour la masquer - essayez aussi les boutons de zoom",
        "b3": "3. Le bouton main déplace la vue du canevas",
        "b4": "4. Actualiser recharge les calques et réinitialise la vue",
        "b5": "5. Le bouton cible centre vos brins",
        "b_end": "Faites un clic droit sur tout bouton dont vous doutez - terminé !",
        "m_title": "Tutoriel : croiser des brins avec un masque",
        "m1": "1. Cliquez sur '{new_strand}', puis faites glisser sur le canevas pour dessiner le brin 1_1",
        "m2": "2. Cliquez sur '{attach}', puis faites glisser depuis l'extrémité de 1_1 pour ajouter le brin 1_2",
        "m3": "3. Cliquez de nouveau sur '{new_strand}' pour commencer l'ensemble 2 - dessinez le brin 2_1",
        "m4": "4. Cliquez sur '{attach}' et ajoutez le brin 2_2 - il passe au-dessus du brin 1_1",
        "m5": "5. Ouvrez l'onglet '{masks}' et cliquez sur '{new_mask}'",
        "m6": "6. Cliquez sur le brin 1_1 - il restera au-dessus",
        "m7": "7. Cliquez maintenant sur le brin 2_2 - il passe sous le brin 1_1",
        "m8": "8. Le calque de masque '1_1_2_2' apparaît dans la liste '{masks}'",
        "m9": "9. Passez de '{strands}' à '{masks}' pour voir chaque liste",
        "m_end": "Les masques restent toujours au-dessus de tous les brins - terminé !",
        "k_title": "Tutoriel : fermer un nœud",
        "k1": "1. Cliquez sur '{new_strand}' et faites glisser pour dessiner le brin 1_1",
        "k2": "2. Cliquez sur '{attach}' et ajoutez le brin 1_2 depuis une extrémité de 1_1",
        "k3": "3. Attachez le brin 1_3 depuis l'autre extrémité de 1_1",
        "k4": "4. Faites un clic droit sur le calque '1_2' et choisissez '{close_knot}'",
        "k5": "5. Les extrémités libres se rejoignent - vous avez fait un nœud fermé !",
    },
    "de": {
        "s_title": "Tutorial: Themen und Sprache",
        "s1": "1. Klicken Sie auf die Schaltfläche Einstellungen (Zahnrad)",
        "s2": "2. Öffnen Sie die Themenliste und wählen Sie '{dark}'",
        "s3": "3. Klicken Sie auf {ok} - die ganze App wechselt das Thema",
        "s4": "4. Öffnen Sie die Einstellungen erneut und wählen Sie '{change_language}'",
        "s5": "5. Wählen Sie eine Sprache und dann {ok} - die Oberfläche wird aktualisiert",
        "s6": "6. Wechseln Sie jederzeit zurück - Einstellungen werden automatisch gespeichert",
        "s_end": "Fertig - machen Sie OpenStrand Studio zu Ihrem!",
        "b_title": "Tutorial: Was bewirken die Schaltflächen im Ebenenpanel?",
        "b1": "1. Halten Sie die rechte Maustaste auf einer Schaltfläche gedrückt, um ihre Beschreibung zu sehen",
        "b2": "2. Loslassen blendet sie aus - probieren Sie auch die Zoom-Schaltflächen",
        "b3": "3. Die Hand-Schaltfläche verschiebt die Ansicht der Zeichenfläche",
        "b4": "4. Aktualisieren lädt die Ebenen neu und setzt die Ansicht zurück",
        "b5": "5. Die Zielscheibe zentriert Ihre Stränge",
        "b_end": "Rechtsklick auf jede unklare Schaltfläche - fertig!",
        "m_title": "Tutorial: Stränge mit einer Maske kreuzen",
        "m1": "1. Klicken Sie auf '{new_strand}' und ziehen Sie auf der Zeichenfläche, um Strang 1_1 zu zeichnen",
        "m2": "2. Klicken Sie auf '{attach}' und ziehen Sie vom Ende von 1_1, um Strang 1_2 anzufügen",
        "m3": "3. Klicken Sie erneut auf '{new_strand}' für Satz 2 - zeichnen Sie Strang 2_1",
        "m4": "4. Klicken Sie auf '{attach}' und fügen Sie Strang 2_2 an - er kreuzt über Strang 1_1",
        "m5": "5. Öffnen Sie den Tab '{masks}' und klicken Sie auf '{new_mask}'",
        "m6": "6. Klicken Sie auf Strang 1_1 - er bleibt oben",
        "m7": "7. Klicken Sie nun auf Strang 2_2 - er läuft unter Strang 1_1",
        "m8": "8. Die Maskenebene '1_1_2_2' erscheint in der Liste '{masks}'",
        "m9": "9. Wechseln Sie zwischen '{strands}' und '{masks}', um jede Liste zu sehen",
        "m_end": "Masken bleiben immer über allen Strängen - fertig!",
        "k_title": "Tutorial: einen Knoten schließen",
        "k1": "1. Klicken Sie auf '{new_strand}' und ziehen Sie, um Strang 1_1 zu zeichnen",
        "k2": "2. Klicken Sie auf '{attach}' und fügen Sie Strang 1_2 an einem Ende von 1_1 an",
        "k3": "3. Fügen Sie Strang 1_3 am anderen Ende von 1_1 an",
        "k4": "4. Rechtsklick auf Ebene '1_2' und '{close_knot}' wählen",
        "k5": "5. Die freien Enden schnappen zusammen - Sie haben einen geschlossenen Knoten erstellt!",
    },
    "it": {
        "s_title": "Tutorial: temi e lingua",
        "s1": "1. Fai clic sul pulsante Impostazioni (ingranaggio)",
        "s2": "2. Apri l'elenco dei temi e scegli '{dark}'",
        "s3": "3. Fai clic su {ok} - tutta l'app cambia tema",
        "s4": "4. Riapri le Impostazioni e scegli '{change_language}'",
        "s5": "5. Scegli una lingua, poi {ok} - l'interfaccia si aggiorna",
        "s6": "6. Puoi tornare indietro quando vuoi - le impostazioni vengono salvate automaticamente",
        "s_end": "Fatto - rendi OpenStrand Studio tuo!",
        "b_title": "Tutorial: a cosa servono i pulsanti del pannello dei livelli?",
        "b1": "1. Tieni premuto il clic destro su un pulsante per vedere la sua descrizione",
        "b2": "2. Rilascia per nasconderla - prova anche i pulsanti dello zoom",
        "b3": "3. Il pulsante a mano sposta la vista della tela",
        "b4": "4. Aggiorna ricarica i livelli e reimposta la vista",
        "b5": "5. Il pulsante bersaglio centra i tuoi trefoli",
        "b_end": "Fai clic destro su ogni pulsante di cui non sei sicuro - fatto!",
        "m_title": "Tutorial: incrociare i trefoli con una maschera",
        "m1": "1. Fai clic su '{new_strand}', poi trascina sulla tela per disegnare il trefolo 1_1",
        "m2": "2. Fai clic su '{attach}', poi trascina dall'estremità di 1_1 per aggiungere il trefolo 1_2",
        "m3": "3. Fai di nuovo clic su '{new_strand}' per iniziare il gruppo 2 - disegna il trefolo 2_1",
        "m4": "4. Fai clic su '{attach}' e aggiungi il trefolo 2_2 - passa sopra il trefolo 1_1",
        "m5": "5. Apri la scheda '{masks}' e fai clic su '{new_mask}'",
        "m6": "6. Fai clic sul trefolo 1_1 - resterà sopra",
        "m7": "7. Ora fai clic sul trefolo 2_2 - passa sotto il trefolo 1_1",
        "m8": "8. Il livello maschera '1_1_2_2' appare nell'elenco '{masks}'",
        "m9": "9. Passa da '{strands}' a '{masks}' per vedere ogni elenco",
        "m_end": "Le maschere restano sempre sopra tutti i trefoli - fatto!",
        "k_title": "Tutorial: chiudere un nodo",
        "k1": "1. Fai clic su '{new_strand}' e trascina per disegnare il trefolo 1_1",
        "k2": "2. Fai clic su '{attach}' e aggiungi il trefolo 1_2 da un'estremità di 1_1",
        "k3": "3. Unisci il trefolo 1_3 dall'altra estremità di 1_1",
        "k4": "4. Fai clic destro sul livello '1_2' e scegli '{close_knot}'",
        "k5": "5. Le estremità libere si agganciano - hai creato un nodo chiuso!",
    },
    "es": {
        "s_title": "Tutorial: temas e idioma",
        "s1": "1. Haz clic en el botón Configuración (engranaje)",
        "s2": "2. Abre la lista de temas y elige '{dark}'",
        "s3": "3. Haz clic en {ok} - toda la aplicación cambia de tema",
        "s4": "4. Abre Configuración de nuevo y elige '{change_language}'",
        "s5": "5. Elige un idioma y luego {ok} - la interfaz se actualiza",
        "s6": "6. Vuelve atrás cuando quieras - los ajustes se guardan automáticamente",
        "s_end": "¡Listo! Haz que OpenStrand Studio sea tuyo",
        "b_title": "Tutorial: ¿para qué sirven los botones del panel de capas?",
        "b1": "1. Mantén el clic derecho sobre un botón para ver su descripción",
        "b2": "2. Suelta para ocultarla - prueba también los botones de zoom",
        "b3": "3. El botón de la mano desplaza la vista del lienzo",
        "b4": "4. Actualizar recarga las capas y restablece la vista",
        "b5": "5. El botón de la diana centra tus cordones",
        "b_end": "Haz clic derecho en cualquier botón del que dudes - ¡listo!",
        "m_title": "Tutorial: cruzar cordones con una máscara",
        "m1": "1. Haz clic en '{new_strand}' y arrastra sobre el lienzo para dibujar el cordón 1_1",
        "m2": "2. Haz clic en '{attach}' y arrastra desde el extremo de 1_1 para añadir el cordón 1_2",
        "m3": "3. Haz clic otra vez en '{new_strand}' para empezar el conjunto 2 - dibuja el cordón 2_1",
        "m4": "4. Haz clic en '{attach}' y añade el cordón 2_2 - cruza por encima del cordón 1_1",
        "m5": "5. Abre la pestaña '{masks}' y haz clic en '{new_mask}'",
        "m6": "6. Haz clic en el cordón 1_1 - se quedará encima",
        "m7": "7. Ahora haz clic en el cordón 2_2 - pasa por debajo del cordón 1_1",
        "m8": "8. La capa de máscara '1_1_2_2' aparece en la lista '{masks}'",
        "m9": "9. Cambia entre '{strands}' y '{masks}' para ver cada lista",
        "m_end": "Las máscaras siempre quedan sobre todos los cordones - ¡listo!",
        "k_title": "Tutorial: cerrar un nudo",
        "k1": "1. Haz clic en '{new_strand}' y arrastra para dibujar el cordón 1_1",
        "k2": "2. Haz clic en '{attach}' y añade el cordón 1_2 desde un extremo de 1_1",
        "k3": "3. Une el cordón 1_3 desde el otro extremo de 1_1",
        "k4": "4. Haz clic derecho en la capa '1_2' y elige '{close_knot}'",
        "k5": "5. Los extremos libres se unen - ¡has hecho un nudo cerrado!",
    },
    "pt": {
        "s_title": "Tutorial: temas e idioma",
        "s1": "1. Clique no botão Configurações (engrenagem)",
        "s2": "2. Abra a lista de temas e escolha '{dark}'",
        "s3": "3. Clique em {ok} - o aplicativo inteiro muda de tema",
        "s4": "4. Abra as Configurações novamente e escolha '{change_language}'",
        "s5": "5. Escolha um idioma e depois {ok} - a interface é atualizada",
        "s6": "6. Volte quando quiser - as configurações são salvas automaticamente",
        "s_end": "Pronto - deixe o OpenStrand Studio com a sua cara!",
        "b_title": "Tutorial: para que servem os botões do painel de camadas?",
        "b1": "1. Mantenha o botão direito pressionado sobre um botão para ver sua descrição",
        "b2": "2. Solte para ocultá-la - experimente também os botões de zoom",
        "b3": "3. O botão da mão desloca a vista da tela",
        "b4": "4. Atualizar recarrega as camadas e redefine a vista",
        "b5": "5. O botão de alvo centraliza as suas mechas",
        "b_end": "Clique com o botão direito em qualquer botão que não conheça - pronto!",
        "m_title": "Tutorial: cruzar mechas com uma máscara",
        "m1": "1. Clique em '{new_strand}' e arraste na tela para desenhar a mecha 1_1",
        "m2": "2. Clique em '{attach}' e arraste a partir da ponta de 1_1 para adicionar a mecha 1_2",
        "m3": "3. Clique em '{new_strand}' de novo para iniciar o conjunto 2 - desenhe a mecha 2_1",
        "m4": "4. Clique em '{attach}' e adicione a mecha 2_2 - ela cruza por cima da mecha 1_1",
        "m5": "5. Abra a aba '{masks}' e clique em '{new_mask}'",
        "m6": "6. Clique na mecha 1_1 - ela ficará por cima",
        "m7": "7. Agora clique na mecha 2_2 - ela passa por baixo da mecha 1_1",
        "m8": "8. A camada de máscara '1_1_2_2' aparece na lista '{masks}'",
        "m9": "9. Alterne entre '{strands}' e '{masks}' para ver cada lista",
        "m_end": "As máscaras ficam sempre acima de todas as mechas - pronto!",
        "k_title": "Tutorial: fechar um nó",
        "k1": "1. Clique em '{new_strand}' e arraste para desenhar a mecha 1_1",
        "k2": "2. Clique em '{attach}' e adicione a mecha 1_2 a partir de uma ponta de 1_1",
        "k3": "3. Una a mecha 1_3 a partir da outra ponta de 1_1",
        "k4": "4. Clique com o botão direito na camada '1_2' e escolha '{close_knot}'",
        "k5": "5. As pontas livres se encaixam - você fez um nó fechado!",
    },
    "he": {
        "s_title": "מדריך: ערכות נושא ושפה",
        "s1": "1. לחצו על כפתור ההגדרות (גלגל השיניים)",
        "s2": "2. פתחו את רשימת ערכות הנושא ובחרו '{dark}'",
        "s3": "3. לחצו על {ok} - כל האפליקציה מחליפה ערכת נושא",
        "s4": "4. פתחו שוב את ההגדרות ובחרו '{change_language}'",
        "s5": "5. בחרו שפה ואז {ok} - הממשק מתעדכן",
        "s6": "6. אפשר לחזור בכל רגע - ההגדרות נשמרות אוטומטית",
        "s_end": "זהו - הפכו את OpenStrand Studio לשלכם!",
        "b_title": "מדריך: מה עושים הכפתורים בחלונית השכבות?",
        "b1": "1. לחצו לחיצה ימנית ארוכה על כל כפתור כדי לראות את התיאור שלו",
        "b2": "2. שחררו כדי להסתיר אותו - נסו גם את כפתורי הזום",
        "b3": "3. כפתור היד מזיז את תצוגת הקנבס",
        "b4": "4. רענון טוען מחדש את השכבות ומאפס את התצוגה",
        "b5": "5. כפתור המטרה ממרכז את החוטים שלכם",
        "b_end": "לחצו לחיצה ימנית על כל כפתור שאינכם בטוחים לגביו - זהו!",
        "m_title": "מדריך: חציית חוטים באמצעות מסכה",
        "m1": "1. לחצו על '{new_strand}' וגררו על הקנבס כדי לצייר את חוט 1_1",
        "m2": "2. לחצו על '{attach}' וגררו מקצה 1_1 כדי להוסיף את חוט 1_2",
        "m3": "3. לחצו שוב על '{new_strand}' כדי להתחיל קבוצה 2 - ציירו את חוט 2_1",
        "m4": "4. לחצו על '{attach}' והוסיפו את חוט 2_2 - הוא חוצה מעל חוט 1_1",
        "m5": "5. פתחו את הלשונית '{masks}' ולחצו על '{new_mask}'",
        "m6": "6. לחצו על חוט 1_1 - הוא יישאר למעלה",
        "m7": "7. עכשיו לחצו על חוט 2_2 - הוא עובר מתחת לחוט 1_1",
        "m8": "8. שכבת המסכה '1_1_2_2' מופיעה ברשימה '{masks}'",
        "m9": "9. עברו בין '{strands}' ל-'{masks}' כדי לראות כל רשימה",
        "m_end": "מסכות תמיד נשארות מעל כל החוטים - זהו!",
        "k_title": "מדריך: סגירת קשר",
        "k1": "1. לחצו על '{new_strand}' וגררו כדי לצייר את חוט 1_1",
        "k2": "2. לחצו על '{attach}' והוסיפו את חוט 1_2 מאחד הקצוות של 1_1",
        "k3": "3. חברו את חוט 1_3 מהקצה השני של 1_1",
        "k4": "4. לחצו לחיצה ימנית על השכבה '1_2' ובחרו '{close_knot}'",
        "k5": "5. הקצוות החופשיים מתחברים - יצרתם קשר סגור!",
    },
    "ru": {
        "s_title": "Урок: тема и язык",
        "s1": "1. Нажмите кнопку «Настройки» (шестерёнка)",
        "s2": "2. Откройте список тем и выберите «{dark}»",
        "s3": "3. Нажмите «{ok}» - всё приложение сменит тему",
        "s4": "4. Снова откройте настройки и выберите «{change_language}»",
        "s5": "5. Выберите язык и нажмите «{ok}» - интерфейс обновится",
        "s6": "6. Вернуться можно в любой момент - настройки сохраняются автоматически",
        "s_end": "Готово - настройте OpenStrand Studio под себя!",
        "b_title": "Урок: что делают кнопки панели слоёв?",
        "b1": "1. Удерживайте правую кнопку мыши на любой кнопке, чтобы увидеть её описание",
        "b2": "2. Отпустите, чтобы скрыть его - попробуйте и кнопки масштаба",
        "b3": "3. Кнопка с рукой перемещает вид холста",
        "b4": "4. «Обновить» перезагружает слои и сбрасывает вид",
        "b5": "5. Кнопка-мишень центрирует ваши пряди",
        "b_end": "Щёлкните правой кнопкой по любой неясной кнопке - готово!",
        "m_title": "Урок: пересечение прядей с помощью маски",
        "m1": "1. Нажмите «{new_strand}» и проведите по холсту, чтобы нарисовать прядь 1_1",
        "m2": "2. Нажмите «{attach}» и проведите от конца 1_1, чтобы добавить прядь 1_2",
        "m3": "3. Снова нажмите «{new_strand}», чтобы начать набор 2 - нарисуйте прядь 2_1",
        "m4": "4. Нажмите «{attach}» и добавьте прядь 2_2 - она пересекает прядь 1_1 сверху",
        "m5": "5. Откройте вкладку «{masks}» и нажмите «{new_mask}»",
        "m6": "6. Щёлкните по пряди 1_1 - она останется сверху",
        "m7": "7. Теперь щёлкните по пряди 2_2 - она пройдёт под прядью 1_1",
        "m8": "8. Слой маски «1_1_2_2» появится в списке «{masks}»",
        "m9": "9. Переключайтесь между «{strands}» и «{masks}», чтобы увидеть каждый список",
        "m_end": "Маски всегда остаются поверх всех прядей - готово!",
        "k_title": "Урок: замыкание узла",
        "k1": "1. Нажмите «{new_strand}» и проведите, чтобы нарисовать прядь 1_1",
        "k2": "2. Нажмите «{attach}» и добавьте прядь 1_2 от одного конца 1_1",
        "k3": "3. Присоедините прядь 1_3 от другого конца 1_1",
        "k4": "4. Щёлкните правой кнопкой по слою «1_2» и выберите «{close_knot}»",
        "k5": "5. Свободные концы соединились - вы создали закрытый узел!",
    },
    "fi": {
        "s_title": "Opas: teema ja kieli",
        "s1": "1. Napsauta Asetukset-painiketta (hammasratas)",
        "s2": "2. Avaa teemaluettelo ja valitse '{dark}'",
        "s3": "3. Napsauta {ok} - koko sovellus vaihtaa teemaa",
        "s4": "4. Avaa Asetukset uudelleen ja valitse '{change_language}'",
        "s5": "5. Valitse kieli ja napsauta {ok} - käyttöliittymä päivittyy",
        "s6": "6. Voit palata takaisin milloin tahansa - asetukset tallentuvat automaattisesti",
        "s_end": "Siinä kaikki - tee OpenStrand Studiosta omasi!",
        "b_title": "Opas: mitä tasopaneelin painikkeet tekevät?",
        "b1": "1. Pidä hiiren oikeaa painiketta painettuna painikkeen päällä nähdäksesi sen kuvauksen",
        "b2": "2. Vapauta piilottaaksesi sen - kokeile myös zoomauspainikkeita",
        "b3": "3. Käsipainike siirtää piirtoalueen näkymää",
        "b4": "4. Päivitä lataa tasot uudelleen ja palauttaa näkymän",
        "b5": "5. Kohdepainike keskittää säikeesi",
        "b_end": "Napsauta hiiren oikealla painikkeella mitä tahansa epäselvää painiketta - valmis!",
        "m_title": "Opas: säikeiden ristiminen maskilla",
        "m1": "1. Napsauta '{new_strand}' ja vedä piirtoalueella piirtääksesi säikeen 1_1",
        "m2": "2. Napsauta '{attach}' ja vedä säikeen 1_1 päästä lisätäksesi säikeen 1_2",
        "m3": "3. Napsauta '{new_strand}' uudelleen aloittaaksesi sarjan 2 - piirrä säie 2_1",
        "m4": "4. Napsauta '{attach}' ja lisää säie 2_2 - se ylittää säikeen 1_1 päältä",
        "m5": "5. Avaa välilehti '{masks}' ja napsauta '{new_mask}'",
        "m6": "6. Napsauta säiettä 1_1 - se jää päälle",
        "m7": "7. Napsauta nyt säiettä 2_2 - se kulkee säikeen 1_1 alta",
        "m8": "8. Maskitaso '1_1_2_2' ilmestyy luetteloon '{masks}'",
        "m9": "9. Vaihda välillä '{strands}' ja '{masks}' nähdäksesi kunkin luettelon",
        "m_end": "Maskit pysyvät aina kaikkien säikeiden päällä - valmis!",
        "k_title": "Opas: solmun sulkeminen",
        "k1": "1. Napsauta '{new_strand}' ja vedä piirtääksesi säikeen 1_1",
        "k2": "2. Napsauta '{attach}' ja lisää säie 1_2 säikeen 1_1 yhdestä päästä",
        "k3": "3. Liitä säie 1_3 säikeen 1_1 toisesta päästä",
        "k4": "4. Napsauta tasoa '1_2' hiiren oikealla painikkeella ja valitse '{close_knot}'",
        "k5": "5. Vapaat päät tarttuvat yhteen - teit suljetun solmun!",
    },
    "sv": {
        "s_title": "Handledning: tema och språk",
        "s1": "1. Klicka på knappen Inställningar (kugghjulet)",
        "s2": "2. Öppna temalistan och välj '{dark}'",
        "s3": "3. Klicka på {ok} - hela appen byter tema",
        "s4": "4. Öppna Inställningar igen och välj '{change_language}'",
        "s5": "5. Välj ett språk och klicka sedan på {ok} - gränssnittet uppdateras",
        "s6": "6. Byt tillbaka när du vill - inställningarna sparas automatiskt",
        "s_end": "Så där - gör OpenStrand Studio till ditt eget!",
        "b_title": "Handledning: vad gör knapparna i lagerpanelen?",
        "b1": "1. Håll högerklick på en knapp för att se dess beskrivning",
        "b2": "2. Släpp för att dölja den - prova zoomknapparna också",
        "b3": "3. Handknappen panorerar arbetsytan",
        "b4": "4. Uppdatera laddar om lagren och återställer vyn",
        "b5": "5. Målknappen centrerar dina strängar",
        "b_end": "Högerklicka på valfri knapp du är osäker på - klart!",
        "m_title": "Handledning: korsa strängar med en mask",
        "m1": "1. Klicka på '{new_strand}' och dra på arbetsytan för att rita sträng 1_1",
        "m2": "2. Klicka på '{attach}' och dra från änden av 1_1 för att lägga till sträng 1_2",
        "m3": "3. Klicka på '{new_strand}' igen för att starta grupp 2 - rita sträng 2_1",
        "m4": "4. Klicka på '{attach}' och lägg till sträng 2_2 - den korsar över sträng 1_1",
        "m5": "5. Öppna fliken '{masks}' och klicka på '{new_mask}'",
        "m6": "6. Klicka på sträng 1_1 - den hamnar överst",
        "m7": "7. Klicka nu på sträng 2_2 - den går under sträng 1_1",
        "m8": "8. Masklagret '1_1_2_2' visas i listan '{masks}'",
        "m9": "9. Växla mellan '{strands}' och '{masks}' för att se varje lista",
        "m_end": "Masker ligger alltid ovanpå alla strängar - klart!",
        "k_title": "Handledning: sluta en knop",
        "k1": "1. Klicka på '{new_strand}' och dra för att rita sträng 1_1",
        "k2": "2. Klicka på '{attach}' och lägg till sträng 1_2 från ena änden av 1_1",
        "k3": "3. Fäst sträng 1_3 från andra änden av 1_1",
        "k4": "4. Högerklicka på lagret '1_2' och välj '{close_knot}'",
        "k5": "5. De fria ändarna fäster vid varandra - du har gjort en sluten knop!",
    },
    "ja": {
        "s_title": "チュートリアル: テーマと言語",
        "s1": "1. 設定（歯車）ボタンをクリックします",
        "s2": "2. テーマのドロップダウンを開いて「{dark}」を選びます",
        "s3": "3. 「{ok}」をクリックすると、アプリ全体のテーマが切り替わります",
        "s4": "4. もう一度設定を開いて「{change_language}」を選びます",
        "s5": "5. 言語を選んで「{ok}」をクリックすると、表示が切り替わります",
        "s6": "6. いつでも元に戻せます - 設定は自動的に保存されます",
        "s_end": "完了です - OpenStrand Studio を自分好みに！",
        "b_title": "チュートリアル: レイヤーパネルのボタンの役割",
        "b1": "1. ボタンを右クリックしたままにすると説明が表示されます",
        "b2": "2. 離すと説明が消えます - ズームボタンも試してみましょう",
        "b3": "3. 手のボタンでキャンバスの表示を移動できます",
        "b4": "4. 更新ボタンはレイヤーを再読み込みして表示をリセットします",
        "b5": "5. ターゲットボタンでストランドを中央に配置します",
        "b_end": "よくわからないボタンは右クリック - 完了です！",
        "m_title": "チュートリアル: マスクでストランドを交差させる",
        "m1": "1. 「{new_strand}」をクリックし、キャンバス上でドラッグしてストランド 1_1 を描きます",
        "m2": "2. 「{attach}」をクリックし、1_1 の端からドラッグしてストランド 1_2 を追加します",
        "m3": "3. もう一度「{new_strand}」をクリックしてセット 2 を始め、ストランド 2_1 を描きます",
        "m4": "4. 「{attach}」をクリックしてストランド 2_2 を追加します - ストランド 1_1 の上を横切ります",
        "m5": "5. 「{masks}」タブを開き、「{new_mask}」をクリックします",
        "m6": "6. ストランド 1_1 をクリックします - こちらが上に残ります",
        "m7": "7. 次にストランド 2_2 をクリックします - ストランド 1_1 の下を通ります",
        "m8": "8. マスクレイヤー「1_1_2_2」が「{masks}」の一覧に表示されます",
        "m9": "9. 「{strands}」と「{masks}」を切り替えて、それぞれの一覧を確認できます",
        "m_end": "マスクは常にすべてのストランドの上にあります - 完了です！",
        "k_title": "チュートリアル: 結び目を閉じる",
        "k1": "1. 「{new_strand}」をクリックし、ドラッグしてストランド 1_1 を描きます",
        "k2": "2. 「{attach}」をクリックし、1_1 の一方の端からストランド 1_2 を追加します",
        "k3": "3. 1_1 のもう一方の端からストランド 1_3 を接続します",
        "k4": "4. レイヤー「1_2」を右クリックして「{close_knot}」を選びます",
        "k5": "5. 自由な端がつながります - 閉じた結び目の完成です！",
    },
    "zh": {
        "s_title": "教程: 主题和语言",
        "s1": "1. 点击设置（齿轮）按钮",
        "s2": "2. 打开主题下拉列表，选择“{dark}”",
        "s3": "3. 点击“{ok}” - 整个应用将切换主题",
        "s4": "4. 再次打开设置，选择“{change_language}”",
        "s5": "5. 选择一种语言，然后点击“{ok}” - 界面随即更新",
        "s6": "6. 随时可以切换回来 - 设置会自动保存",
        "s_end": "完成 - 打造属于你的 OpenStrand Studio！",
        "b_title": "教程: 图层面板中的按钮有什么作用？",
        "b1": "1. 在任意按钮上按住右键即可查看其说明",
        "b2": "2. 松开即可隐藏说明 - 也试试缩放按钮",
        "b3": "3. 手形按钮用于平移画布视图",
        "b4": "4. 刷新按钮会重新加载图层并重置视图",
        "b5": "5. 靶心按钮会将绳股居中",
        "b_end": "不确定的按钮都可以右键查看 - 完成！",
        "m_title": "教程: 用遮罩交叉绳股",
        "m1": "1. 点击“{new_strand}”，然后在画布上拖动以绘制绳股 1_1",
        "m2": "2. 点击“{attach}”，然后从 1_1 的末端拖动以添加绳股 1_2",
        "m3": "3. 再次点击“{new_strand}”开始第 2 组 - 绘制绳股 2_1",
        "m4": "4. 点击“{attach}”并添加绳股 2_2 - 它从绳股 1_1 上方穿过",
        "m5": "5. 打开“{masks}”标签页，点击“{new_mask}”",
        "m6": "6. 点击绳股 1_1 - 它将保持在上方",
        "m7": "7. 现在点击绳股 2_2 - 它从绳股 1_1 下方穿过",
        "m8": "8. 遮罩图层“1_1_2_2”出现在“{masks}”列表中",
        "m9": "9. 在“{strands}”和“{masks}”之间切换，查看各自的列表",
        "m_end": "遮罩始终位于所有绳股之上 - 完成！",
        "k_title": "教程: 闭合绳结",
        "k1": "1. 点击“{new_strand}”，拖动以绘制绳股 1_1",
        "k2": "2. 点击“{attach}”，从 1_1 的一端添加绳股 1_2",
        "k3": "3. 从 1_1 的另一端连接绳股 1_3",
        "k4": "4. 右键点击图层“1_2”，选择“{close_knot}”",
        "k5": "5. 自由端合拢 - 你制作了一个闭合绳结！",
    },
}

LANGUAGES = list(CAPTIONS)
